Add docker build and CI config
OneSignal/passenger_exporter pull request #1
Opened 2021-08-17 10:38 UTC by alex-richman-onesignal

- Add docker build and CI config

2021-08-17 12:13 UTC, niels-s requested changes

2021-08-17 12:13 UTC, niels-s commented on .circleci/config.yml
> +          requires:
Can we only publish on master branch runs?

2021-08-24 09:04 UTC, niels-s approved these changes

2021-08-24 15:20 UTC, merged

2021-08-30 12:12 UTC, magec commented
:clap: